//  Copyright 2021 Allen Lee
//
//  Author:  Allen Lee (alee@meoworkshop.org)
//  
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//
//  For more information, please refer to https://opensource.org/licenses/mit-license.php
//
//  ------------------------------------------------------------------------------------------------  //
//
//  Graphical Sprite Assets under CC BY-SA 3.0
//  For more information, please refer to https://creativecommons.org/licenses/by-sa/3.0/legalcode
//
//  ------------------------------------------------------------------------------------------------  //

#ifndef SRC_ASSETS_BM_ASSETS_TELEPHONE_H_
#define SRC_ASSETS_BM_ASSETS_TELEPHONE_H_

#include "arm_math.h"

extern uint8_t BM_ASSETS_TELEPHONE_ICON[];

extern uint8_t BM_ASSETS_TELEPHONE_PHONEBOOK_BKGND[];
extern uint8_t BM_ASSETS_TELEPHONE_HIPSTER_BKGND[];
extern uint8_t BM_ASSETS_TELEPHONE_SPY_BKGND[];
extern uint8_t BM_ASSETS_TELEPHONE_SPY_BKGND_MASK[];

extern int32_t BM_ASSETS_TELEPHONE_PAYPHONE_FACE_WIDTH;
extern int32_t BM_ASSETS_TELEPHONE_PAYPHONE_FACE_HEIGHT;
extern uint8_t BM_ASSETS_TELEPHONE_PAYPHONE_FACE[];
extern uint8_t BM_ASSETS_TELEPHONE_PAYPHONE_FACE_MASK[];

extern int32_t BM_ASSETS_TELEPHONE_CALLER_PHONE_ACTIVE_WIDTH;
extern int32_t BM_ASSETS_TELEPHONE_CALLER_PHONE_ACTIVE_HEIGHT;
extern uint8_t BM_ASSETS_TELEPHONE_CALLER_PHONE_ACTIVE[];
extern uint8_t BM_ASSETS_TELEPHONE_CALLER_PHONE_MASK[];

extern int32_t BM_ASSETS_TELEPHONE_CALLER_PHONE_INACTIVE_WIDTH;
extern int32_t BM_ASSETS_TELEPHONE_CALLER_PHONE_INACTIVE_HEIGHT;
extern uint8_t BM_ASSETS_TELEPHONE_CALLER_PHONE_INACTIVE[];

extern int32_t BM_ASSETS_TELEPHONE_CALLER_PHONE_NOISE_WIDTH;
extern int32_t BM_ASSETS_TELEPHONE_CALLER_PHONE_NOISE_HEIGHT;
extern uint8_t BM_ASSETS_TELEPHONE_CALLER_PHONE_NOISE[];
extern uint8_t BM_ASSETS_TELEPHONE_CALLER_PHONE_NOISE_MASK[];

extern int32_t BM_ASSETS_TELEPHONE_CALLER_MUSIC_NOTES_WIDTH;
extern int32_t BM_ASSETS_TELEPHONE_CALLER_MUSIC_NOTES_HEIGHT;
extern uint8_t BM_ASSETS_TELEPHONE_CALLER_MUSIC_NOTES[];
extern uint8_t BM_ASSETS_TELEPHONE_CALLER_MUSIC_NOTES_MASK[];

extern int32_t BM_ASSETS_TELEPHONE_HIPSTER_CAT_WIDTH;
extern int32_t BM_ASSETS_TELEPHONE_HIPSTER_CAT_HEIGHT;
extern uint8_t BM_ASSETS_TELEPHONE_HIPSTER_CAT[];
// extern uint8_t BM_ASSETS_TELEPHONE_CALLER_PHONE_MASK[];

extern int32_t BM_ASSETS_TELEPHONE_HIPSTER_CAT_TALK_WIDTH;
extern int32_t BM_ASSETS_TELEPHONE_HIPSTER_CAT_TALK_HEIGHT;
extern uint8_t BM_ASSETS_TELEPHONE_HIPSTER_CAT_TALK[];
// extern uint8_t BM_ASSETS_TELEPHONE_HIPSTER_CAT_TALK_MASK[];

extern int32_t BM_ASSETS_TELEPHONE_HIPSTER_CAT_PHONE_NOISE_WIDTH;
extern int32_t BM_ASSETS_TELEPHONE_HIPSTER_CAT_PHONE_NOISE_HEIGHT;
extern uint8_t BM_ASSETS_TELEPHONE_HIPSTER_CAT_PHONE_NOISE[];

extern int32_t BM_ASSETS_TELEPHONE_HIPSTER_CAT_MUSIC_NOTES_WIDTH;
extern int32_t BM_ASSETS_TELEPHONE_HIPSTER_CAT_MUSIC_NOTES_HEIGHT;
extern uint8_t BM_ASSETS_TELEPHONE_HIPSTER_CAT_MUSIC_NOTES[];

extern int32_t BM_ASSETS_TELEPHONE_HIPSTER_CAT_PHONE_INACTIVE_WIDTH;
extern int32_t BM_ASSETS_TELEPHONE_HIPSTER_CAT_PHONE_INACTIVE_HEIGHT;
extern uint8_t BM_ASSETS_TELEPHONE_HIPSTER_CAT_PHONE_INACTIVE[];
// extern uint8_t BM_ASSETS_TELEPHONE_HIPSTER_CAT_PHONE_INACTIVE_MASK[];

extern int32_t BM_ASSETS_TELEPHONE_HIPSTER_CAT_PHONE_ACTIVE_WIDTH;
extern int32_t BM_ASSETS_TELEPHONE_HIPSTER_CAT_PHONE_ACTIVE_HEIGHT;
extern uint8_t BM_ASSETS_TELEPHONE_HIPSTER_CAT_PHONE_ACTIVE[];
// extern uint8_t BM_ASSETS_TELEPHONE_HIPSTER_CAT_PHONE_ACTIVE_MASK[];

extern int32_t BM_ASSETS_TELEPHONE_HIPSTER_CAT_PROPELLER_WIDTH;
extern int32_t BM_ASSETS_TELEPHONE_HIPSTER_CAT_PROPELLER_HEIGHT;
extern int32_t BM_ASSETS_TELEPHONE_HIPSTER_CAT_PROPELLER_NUM_FRAMES;
extern uint8_t BM_ASSETS_TELEPHONE_HIPSTER_CAT_PROPELLER[];
// extern uint8_t BM_ASSETS_TELEPHONE_HIPSTER_CAT_PROPELLER_MASK[];

extern int32_t BM_ASSETS_TELEPHONE_PHONE_BOOK_SELECTOR_WIDTH;
extern int32_t BM_ASSETS_TELEPHONE_PHONE_BOOK_SELECTOR_HEIGHT;
extern uint8_t BM_ASSETS_TELEPHONE_PHONE_BOOK_SELECTOR[];
// extern uint8_t BM_ASSETS_TELEPHONE_PHONE_BOOK_SELECTOR_MASK[];

extern int32_t BM_ASSETS_TELEPHONE_SPY_CAT_WIDTH;
extern int32_t BM_ASSETS_TELEPHONE_SPY_CAT_HEIGHT;
extern uint8_t BM_ASSETS_TELEPHONE_SPY_CAT[];
extern uint8_t BM_ASSETS_TELEPHONE_SPY_CAT_MASK[];

extern int32_t BM_ASSETS_TELEPHONE_SPY_CAT_TALK_WIDTH;
extern int32_t BM_ASSETS_TELEPHONE_SPY_CAT_TALK_HEIGHT;
extern uint8_t BM_ASSETS_TELEPHONE_SPY_CAT_TALK[];
extern uint8_t BM_ASSETS_TELEPHONE_SPY_CAT_TALK_MASK[];

extern int32_t BM_ASSETS_TELEPHONE_SPY_CAT_PHONE_INACTIVE_WIDTH;
extern int32_t BM_ASSETS_TELEPHONE_SPY_CAT_PHONE_INACTIVE_HEIGHT;
extern uint8_t BM_ASSETS_TELEPHONE_SPY_CAT_PHONE_INACTIVE[];
extern uint8_t BM_ASSETS_TELEPHONE_SPY_CAT_PHONE_MASK[];

extern int32_t BM_ASSETS_TELEPHONE_SPY_CAT_PHONE_ACTIVE_WIDTH;
extern int32_t BM_ASSETS_TELEPHONE_SPY_CAT_PHONE_ACTIVE_HEIGHT;
extern uint8_t BM_ASSETS_TELEPHONE_SPY_CAT_PHONE_ACTIVE[];

extern int32_t BM_ASSETS_TELEPHONE_SPY_CAT_SPEECH_WIDTH;
extern int32_t BM_ASSETS_TELEPHONE_SPY_CAT_SPEECH_HEIGHT;
extern uint8_t BM_ASSETS_TELEPHONE_SPY_CAT_SPEECH[];
extern uint8_t BM_ASSETS_TELEPHONE_SPY_CAT_SPEECH_MASK[];

extern int32_t BM_ASSETS_TELEPHONE_SPOTLIGHT_NUM_FRAMES;
extern uint8_t BM_ASSETS_TELEPHONE_SPOTLIGHT[];
extern uint8_t BM_ASSETS_TELEPHONE_SPOTLIGHT_MASK[];

#endif /* SRC_ASSETS_BM_ASSETS_TELEPHONE_H_ */
